### ISSUE TITLE
List of tools

### ISSUE THREAD

**Issue by robi-y** [jce-il/GAE-word-fun#1]
Python 2.7.8
GAE ?

**Comment by MeLight** [comment]
Python 2.7.8
App Engine SDK
TortoiseGit

Should I write it in a doc somewhere?

**Comment by robi-y** [comment]
Thanks, I'll track it

**Comment by robi-y** [comment]
Is this OK with you? https://docs.google.com/forms/d/1zlBJ4l2n9x99HdrGE21cBhELxpfqN0lHVKp6ECD-M4c/edit

**Comment by MeLight** [comment]
The submission form looks good. Do I check it in the linked Google Spreadsheet?

**Comment by robi-y** [comment]
Yep, we need also to think of easy way to transform grades to the excel
grade book maybe based on github or id

**Comment by MeLight** [comment]
I think ID is most appropriate, as it's already in the excel

**Comment by robi-y** [comment]
ok, I suppose you could sort by id and then just move it to the excell
