### ISSUE TITLE
Project 1 Instructions

### ISSUE THREAD

**Issue by robi-y** [jce-il/GAE-word-fun#11]
@MeLight please review the [instructions](http://jce-il.github.io/se-class/project/se15b-proj01-idea.pdf) for the 1st project assignment and let me know if you have comments.
Currently it lacks submission instructions, except for putting links on the wiki Meeting page:
Pro: simple, cons: we'll have to map their names to ids in grade sheet for this assignent

**Comment by MeLight** [comment]
This 1st assignment is personal, right?

**Comment by robi-y** [comment]
yes

**Comment by MeLight** [comment]
Just making sure that I'm getting this right, I'll need to go through 60 presentation and docs?

**Comment by robi-y** [comment]
They prepare it in couples (would you like to allow triples?)
BTW they are 55 students, so ~25 submissions
I give some of the grades during presentation mostly about presenting it,
and you also review it - maybe we can also join forces

**Comment by MeLight** [comment]
I think couples is good. I'm open to joining forces - so let me know if you have any ideas.

Where do I add the submission instructions? I think an email with ID's and links to the presentation/docs would be sufficient - unless you know of a better mechanism

**Comment by robi-y** [comment]
We can schedule a meeting on Tue./Wed. to go over a few submissions and
maybe after agreeing on indicators to split the rest
Submission - the first one is more difficult, since they don't know to use
git. Currently the [instructions](http://jce-il.github.io/se-class/project/se15b-proj01-idea.pdf) say that
they should provide links in the wiki. It's a good idea to have them send
an official mail, so I'll add it to instructions

**Comment by MeLight** [comment]
Yes, emails would be best in such case. It would also be helpful if the subject is structured like:
Ex1 student1_id student2_id

the submission email is yuri.jce2015@gmail.com

**Comment by robi-y** [comment]
done http://jce-il.github.io/se-class/project/se15b-proj01-idea.pdf

**Comment by MeLight** [comment]
Perfect, thanks. Closing

**Comment by robi-y** [comment]
I see the election day is next Tue. we should think if to move this
assignment over to Wed. and maybe do it together or reschedule to the week
after?

**Comment by MeLight** [comment]
Works for me
