### ISSUE TITLE
Submission Form for personal homework

### ISSUE THREAD

**Issue by robi-y** [jce-il/GAE-word-fun#3]

**Comment by MeLight** [comment]
Can you send me an example please?

**Comment by robi-y** [comment]
I thought I posted the [link](https://docs.google.com/forms/d/1zlBJ4l2n9x99HdrGE21cBhELxpfqN0lHVKp6ECD-M4c/viewform) here already - also added the link to the wiki sidebar
@MeLight r u ok with it?

**Comment by MeLight** [comment]
Looks good to me
