### ISSUE TITLE
Prepare Master Grades Sheet

### ISSUE THREAD

**Issue by robi-y** [jce-il/GAE-word-fun#6]

**Comment by robi-y** [comment]
@MeLight please have a look and let's discuss it before presenting to class

**Comment by MeLight** [comment]
I looked at it - can't say I have ideas on how to simplify it

**Comment by robi-y** [comment]
Actually, i wanted to add another column for all iterations for applying
course materials (I removed specific iteration tasks as you suggested, but
I want to encourage them to use thought in the course)

Also, I suggest moving for each crtiteria to a scale of 0-10, instead of
0-100. This might simplify grading for us. I suggest as a rule giving 8/10
for reasonable submission. The problem is that some of the criteria are
very technical, e.g. opening a repo, and there, there is no reason not to
give full points.

I suggest we will discuss it sometime after the course starts, but we
should agree on the 1st assignments.

**Comment by MeLight** [comment]
Ok cool. First assignment is deploying the Hello GAE app? Or the one after that?

**Comment by robi-y** [comment]
First personal HW is the deployment, I guess this is only
deployed/not-deployed
First project assignment 1 is the idea proposal (only this time in pairs),
is due to the 2nd lecture when they present it

**Comment by MeLight** [comment]
Ok, so the first one is binary - no problem.
We can discuss second one when we meet in school?

**Comment by robi-y** [comment]
Sure thanks
בתאריך 1 במרץ 2015 19:10, "Yuri Sh" notifications@github.com כתב:

**Comment by robi-y** [comment]
@MeLight can you edit it?

**Comment by MeLight** [comment]
Didn't try, but it's no my local machine, so I don't see why not

**Comment by robi-y** [comment]
shared again with your gmail username
